# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256, verbose_name='作者')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.CharField(max_length=8192, verbose_name='内容')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'db_table': 'article',
            },
        ),
    ]
