# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0004_auto_20171023_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_a',
            new_name='title',
        ),
    ]
