# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0005_auto_20171023_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='负责人')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('user_mobile', models.BigIntegerField(verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户表2',
                'verbose_name_plural': '用户表2',
                'db_table': 'user_info2',
            },
        ),
    ]
